

/*
 * Filename: swc_clock_display.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock_display.h"



/* USER CODE START SWC_CLOCK_DISPLAY_INCLUDE */
#include "tft.h"
#include "intToASCII.h"
#include "sc_clock.h"
/* USER CODE END SWC_CLOCK_DISPLAY_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CLOCK_DISPLAY_USERDEFINITIONS */

/* USER CODE END SWC_CLOCK_DISPLAY_USERDEFINITIONS */



/*
* component: swc_CLOCK_display
* cycletime: 250
* description: Runnable for clock display.
* events: 
* name: CLOCK_DISPLAY__run
* shortname: 
* signalIN: so_CLOCK
* signalOUT: 
* task: tsk_display
*/
void CLOCK_DISPLAY__run(RTE_event ev){
	
	/* USER CODE START CLOCK_DISPLAY__run */
    
    
    
	// Read the clock signal data
    SC_CLOCK_data_t clock = RTE_SC_CLOCK_get(&SO_CLOCK_signal);
    // local variable to store the ascii converted data for display.
    static char asciiConvert[30];
    
	// local variables for blinking of the ":' on tft display.
    static uint16_t blinkCounter = 0;
    static uint16_t blink = 0;
    static char blinkingCharacter = ':'; 
    
    // Set cursor and display color associated with 
    // either display or editing mode for hour widget.
    // Convert to ascii and display on tft.
    TFT_setCursor(0+15, ((TFT_height()/2) - 8));
    TFT_setColors(clock.m_hours.m_font.foreground, clock.m_hours.m_font.background);
    intToASCII((uint32_t)clock.m_hours.m_value, (uint8_t*)&asciiConvert, 2);
    TFT_print(asciiConvert);
    
    // Set cursor and display color associated with ':' display.
    // The blinking of ':' on the tft is achieved by toggling logic.
    // The toggle occurs at every call of this runnable viz. 250ms.
    // Convert to ascii and display on tft.
    TFT_setCursor((TFT_width()/2) - 12,((TFT_height()/2) - 8));
    TFT_setColors(WHITE, BLACK);  
    blinkCounter        =   (blinkCounter == 1)? 0 : (blinkCounter + 1);
    blink               =   (blinkCounter == 0)? (!blink) : blink;
    blinkingCharacter   =   (blink == 0)? ':' : ' ';  
    TFT_write(blinkingCharacter);
    
    // Set cursor and display color associated with 
    // either display or editing mode for minute widget.
    // Convert to ascii and display on tft.
    TFT_setCursor((2 * TFT_width()/3) - 12,((TFT_height()/2) - 8));
    TFT_setColors(clock.m_minutes.m_font.foreground, clock.m_minutes.m_font.background);
    intToASCII((uint32_t)clock.m_minutes.m_value, (uint8_t*)&asciiConvert, 2);
    TFT_print(asciiConvert);
        
    if(blink == 0)
    {
        TFT_drawCircle(TFT_width()/2, TFT_height()/2, (TFT_width()/2) - 6, DARKBLUE);
        TFT_drawCircle(TFT_width()/2, TFT_height()/2, (TFT_width()/2) - 3, RED);
    }
    else if(blink == 1)
    {
        TFT_drawCircle(TFT_width()/2, TFT_height()/2, (TFT_width()/2) - 6, BROWN);
        TFT_drawCircle(TFT_width()/2, TFT_height()/2, (TFT_width()/2) - 3, GREEN);
    }
    
    /* USER CODE END CLOCK_DISPLAY__run */
}

/* USER CODE START SWC_CLOCK_DISPLAY_FUNCTIONS */

/* USER CODE END SWC_CLOCK_DISPLAY_FUNCTIONS */

