
/*
 * Filename: tsk_display.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_DISPLAY
#define _H_DEFINE_TSK_DISPLAY

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_DISPLAY_INCLUDES */

/* USER CODE END TSK_DISPLAY_INCLUDES */



/*
* description: Task handling the TFT display
* events: 
* mode: Cyclic
* name: tsk_display
* shortname: display
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: 0
* timertickperiod: 1
*/
DeclareTask(tsk_display);


#endif