

/*
 * Filename: sc_clock_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_clock_type.h"



/* USER CODE START SC_CLOCK_INCLUDE */

/* USER CODE END SC_CLOCK_INCLUDE */


/*
* description: Signalclass of the clock containig the hours and minutes.
* name: sc_CLOCK
* shortname: CLOCK
*/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */

/* USER CODE END SC_CLOCK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_CLOCK signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_CLOCK_driverOut(const SC_CLOCK_data_t  *const data)
{
	/* USER CODE START driverOutSC_CLOCK */

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_CLOCK */
}



