
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_clock.h"
#include "sc_event.h"



/*
* description: A Signal object containing the hours and the minutes of the clock.
* indriver: 0
* name: so_CLOCK
* onDataError: 0
* onDataUpdate: 0
* outdriver: default
* resource: res_clock_Lock
* shortname: CLOCK
* signalclass: sc_CLOCK
* signalpool: sp_common
*/
extern SC_CLOCK_t SO_CLOCK_signal;


/*
* description: A Signal oject containing the Events.
* indriver: default
* name: so_EVENT
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: 0
* resource: res_event_Lock
* shortname: EVENT
* signalclass: sc_EVENT
* signalpool: sp_common
*/
extern SC_EVENT_t SO_EVENT_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

#endif